### ISSUE TITLE
Add option to suppress output of `CoverageReporter.generate_report()`

### ISSUE THREAD

**Issue by StopMotionCuber** [JamalZeynalov/swagger-coverage-py#18]
When using pytest with this project, it's annoying that it produces much output (especially with > 100 API endpoints) when the last test fails, as the output is then printed with pytest. Adding an option to `CoverageReporter` to suppress this output would be great.

Additionally, I found a command injection that is possible with the `swagger_coverage_config` which I'm using as a workaround to suppress the output:
```
    reporter = CoverageReporter(api_name="example", host="http://example.com/")
    # The following is a hack to get a -q into the command
    reporter.swagger_coverage_config = "swagger-coverage-config-example.json -q"
```
While it's probably not a security issue, as `swagger_coverage_config` should not contain untrusted values, it would be great nevertheless to move from `os.system` to something like `subprocess.run` to support whitespace characters in the filename

**Comment by JamalZeynalov** [comment]
@StopMotionCuber Hi,
I consider adding ERRORS_OUTPUT_SUPPRESSED flag managed via environment variables to suppress all logs. Or you need to suppress APIs separately?

**Comment by StopMotionCuber** [comment]
Yeah, that would work for me
