### ISSUE TITLE
Coverage Recorder didn't support swagger basePath

### ISSUE THREAD

**Issue by andrew771027** [JamalZeynalov/swagger-coverage-py#23]
Hi @JamalZeynalov ,

Thanks for the project, let I can measure the coverage for api endpoints from QA side. I was so exciting when i saw the project.
I tried to do some best practice according to readme and other sibling project [allure-reuslts-sample](https://github.com/JamalZeynalov/allure-results-sample), however found some problem.

Sample Code
```
def test_run_coverage_2():
    response: Response = CoverageListener(
        method="get",
        base_url="https://petstore.swagger.io",
        raw_path="/v2/store/order/{orderId}",
        uri_params={"orderId": 1},
        auth=HTTPBasicAuth("username", "password"),
        params={"type": "active"},
    ).response

    assert response.status_code == 200
```

Actual Result:

When i set the raw_path with the basePath (/v2), the coverage recorder didn't capture the request
![image](https://github.com/JamalZeynalov/swagger-coverage-py/assets/17243024/44930d7c-fd87-414e-ac9d-0bd3dac6d3dd)

Expected Result:
I found it is because the coverage recorder didn't handler the basePath (/v2), so that i try to add basePath manually at swagger file.
such as

![image](https://github.com/JamalZeynalov/swagger-coverage-py/assets/17243024/3de5accf-7463-4f6d-a440-43cb269543e7)

Then the recorder record the request well
![image](https://github.com/JamalZeynalov/swagger-coverage-py/assets/17243024/d92cae90-1a77-4936-bfd3-d4a8b7ed1a9f)

I trace the code, it might cause from the java library at [swagger-coverage](https://github.com/viclovsky/swagger-coverage)
Thanks again.

**Comment by JamalZeynalov** [comment]
@andrew771027 I added a param to support base path. Check a new release (version="3.3.0")

**Comment by andrew771027** [comment]
Awesome. Thanks
