### ISSUE TITLE
TypeError: can only concatenate list (not "NoneType") to list

### ISSUE THREAD

**Issue by Sanek0125** [JamalZeynalov/swagger-coverage-py#26]
I send GET request:
<img width="511" alt="Screen 2023-10-26 в 16 24 29" src="https://github.com/JamalZeynalov/swagger-coverage-py/assets/43985376/fdb15a10-38ff-496c-9d08-5d9e1fd6470a">

My error:
<img width="849" alt="Screen 2023-10-26 в 16 25 07" src="https://github.com/JamalZeynalov/swagger-coverage-py/assets/43985376/1040385f-137a-47ef-8057-d606b7605092">

Help me, please:)

**Comment by JamalZeynalov** [comment]
@Sanek0125 I can't reproduce your error. I get 404 error instead. Do you use the latest version? (swagger-coverage 3.3.0)
<img width="568" alt="image" src="https://github.com/JamalZeynalov/swagger-coverage-py/assets/8066700/c6dcb690-8741-4eec-9e73-3e5fe314d01c">

**Comment by Sanek0125** [comment]
I use  the latest version. 
`python freeze` return swagger-coverage==3.3.0
I'm using python 3.11 maybe that's the problem?

Before sending get, I use post to create an entry in petstore

**Comment by Sanek0125** [comment]
My solution to the problem:
```
params = (
            self._get_path_params() + self._get_query_params() + [self._get_body_params()]
        )
```

**Comment by JamalZeynalov** [comment]
@Sanek0125 Thanks. Please create a PR if it works for you. I will test it later and merge if it works for all versions.
