### ISSUE TITLE
Does not support schema in .yaml format

### ISSUE THREAD

**Issue by anriijmind** [JamalZeynalov/swagger-coverage-py#7]
Library fails if add a link to the swagger schema at .yaml format:
`reporter.setup("/api/v1/.../openapi.yaml")`

Error:
`>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py:355: JSONDecodeError`

**Comment by JamalZeynalov** [comment]
Support is added. @anriijmind could you install it from the branch and test how it works?
To install:
`pip install git+https://github.com/JamalZeynalov/swagger-coverage-py.git@support-yaml-format`

**Comment by anriijmind** [comment]
@JamalZeynalov if change `API_DOCS_FORMAT` to the => `os.environ.get("API_DOCS_FORMAT", "yaml") `in the `configs.py` file it works. Folder with swagger-coverage-output generates.

**Comment by JamalZeynalov** [comment]
> @JamalZeynalov if change `API_DOCS_FORMAT` to the => `os.environ.get("API_DOCS_FORMAT", "yaml") `in the `configs.py` file it works. Folder with swagger-coverage-output generates.

Did you install the latest version with all dependencies?
It should also work if you have the environment variable (without changing the code):
```.env
API_DOCS_FORMAT="yaml"
```
